# Generated by Django 3.2 on 2021-04-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.IntegerField(default='', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('feature_1', models.CharField(default='', max_length=50)),
                ('feature_2', models.CharField(default='', max_length=50)),
                ('predicted_disease', models.CharField(default='', max_length=50)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
