# Generated by Django 3.2 on 2021-04-28 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='feature_3',
        ),
        migrations.RemoveField(
            model_name='record',
            name='predicted_disease',
        ),
    ]
