# Generated by Django 3.2 on 2021-05-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_record_feature_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='feature_1',
            field=models.CharField(default='', max_length=50),
        ),
    ]
